import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from 'node:fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to bundle worker code as a string
const workerPlugin = {
	name: 'worker-plugin',
	setup(build) {
		build.onEnd(async () => {
			// Build the worker separately
			const workerResult = await esbuild.build({
				entryPoints: ['src/worker.ts'],
				bundle: true,
				format: 'iife',
				target: 'es2020',
				minify: prod,
				write: false,
				platform: 'browser',
			});

			// Get the worker code as a string
			const workerCode = workerResult.outputFiles[0].text;
			
			// Escape the worker code for injection
			const escapedWorkerCode = JSON.stringify(workerCode);
			
			// Read the main.js file
			let mainCode = fs.readFileSync('main.js', 'utf-8');
			
			// Replace the WORKER_CODE placeholder with the actual worker code
			// This matches both minified (return WORKER_CODE) and non-minified patterns
			mainCode = mainCode.replace(
				/return WORKER_CODE[;]?/g,
				`return ${escapedWorkerCode};`
			);
			
			// Write back the main.js file
			fs.writeFileSync('main.js', mainCode);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [workerPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

